name: OG

# This action will activate at each pull request
on: [pull_request]

# This is the description of the different "Jobs" which will be done.
jobs:
  CheckBuild:
    runs-on: windows-latest
    steps:
      - name: Checks out to current branch
        uses: actions/checkout@v1
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Build program
        run: |
          cd GPlusPlusCompiler
          nuget restore
          cd GPlusPlusCompiler
          msbuild GPlusPlusCompiler.csproj /verbosity:normal /t:Rebuild /p:Configuration=Debug

  AutoTests:
    runs-on: windows-latest
    steps:
      - name: Checks out to current branch
        uses: actions/checkout@v1
      - name: Adds antlr4 as possible commandline
        uses: NiccoMlt/setup-antlr4@v0.0.6
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Generate updated ANTLR lexer and parser
        run: |
          antlr4 -Dlanguage=CSharp -o GPlusPlusCompiler\GPlusPlusCompiler\gen -listener -visitor -lib GPlusPlusCompiler/GPlusPlusCompiler GPlusPlusCompiler/GPlusPlusCompiler\OG.g4
      - name: Rebuild TestUnit to create tests
        run: |
          cd GPlusPlusCompiler
          nuget restore
          cd Tests
          msbuild Tests.csproj /verbosity:normal /t:Rebuild /p:Configuration=Debug
          cd ..
          cd ..
      - name: Run Automated Unittest
        run: |
          NUnitConsole/net20/nunit3-console.exe GPlusPlusCompiler\Tests\bin\Debug\net5.0\TestUnit.dll