name: OG

# This action will activate at each pull request
on: [pull_request]

# This is the description of the different groupings of commands which will be runs.
jobs:
  CheckBuild:
    runs-on: windows-latest
    steps:
      - name: Add a fake 'git' to the PATH to force checkout to download zipball instead
# Check this link to see what this means: https://github.com/actions/checkout/issues/314
        shell: cmd
        run: |
          echo echo hello > git.bat
          echo ::add-path::%CD%
      - name: Checks out to current branch
        uses: actions/checkout@v1.1.0
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Build program
        run: |
          cd OG
          nuget restore
          cd OG
          msbuild OG.csproj /verbosity:normal /t:Rebuild /p:Configuration=Debug

  AutoTests:
    runs-on: windows-latest
    steps:
      - name: Checks out to current branch
        uses: actions/checkout@v2
      - name: Uses java to make use of antlr4 possible
        uses: actions/setup-java@v1
        with:
          java-version: '9.0.4' # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Generate updated ANTLR lexer and parser
        run: |
          java -jar ${{ github.workspace }}\antlr-4.9.2-complete.jar -Dlanguage=CSharp -o OG/OG/gen -listener -visitor -lib OG/OG/gen OG/OG/OG.g4
      - name: Rebuild Tests project to create tests
        run: |
          cd OG
          nuget restore
          cd Tests
          msbuild Tests.csproj /verbosity:normal /t:Rebuild /p:Configuration=Debug
          cd ..
          cd ..
      - name: Run Automated Tests
        run: |
          dotnet test OG\Tests\bin\Debug\net5.0\Tests.dll
