name: OG

# This action will activate at each pull request
on: [pull_request]

# This is the description of the different groupings of commands which will be runs.
jobs:
  CheckBuild:
    runs-on: windows-latest
    steps:
      - name: Checks out to current branch
        uses: actions/checkout@v1
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Build program
        run: |
          cd OG
          nuget restore
          cd OG
          msbuild OG.csproj /verbosity:normal /t:Rebuild /p:Configuration=Debug
          dotnet publish -c Release -r win10-x64 -p:PublishReadyToRun=true --self-contained true
          dotnet publish -c Release -r osx.11.0-x64 -p:PublishReadyToRun=true --self-contained true


  AutoTests:
    runs-on: windows-latest
    steps:
      - name: Checks out to current branch
        uses: actions/checkout@v2
      - name: Uses java to make use of antlr4 possible
        uses: actions/setup-java@v1
        with:
          java-version: '9.0.4' # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Generate updated ANTLR lexer and parser
        run: |
          java -jar ${{ github.workspace }}\antlr-4.9.2-complete.jar -Dlanguage=CSharp -o OG/OG/gen -listener -visitor -lib OG/OG/gen OG/OG/OG.g4
      - name: Rebuild Tests project to create tests
        run: |
          cd OG
          nuget restore
          cd Tests
          msbuild Tests.csproj /verbosity:normal /t:Rebuild /p:Configuration=Debug
          cd ..
          cd ..
      - name: Run Automated Tests
        run: |
          dotnet test OG\Tests\bin\Debug\net5.0\Tests.dll
